module.exports = {
    FUNCTION_CODES: {
        READ_COILS: 1,
        READ_DISCRETE_INPUTS: 2,
        READ_HOLDING_REGISTERS: 3,
        READ_INPUT_REGISTERS: 4,
        WRITE_SINGLE_COIL: 5,
        WRITE_SINGLE_REGISTER: 6,
        WRITE_MULTIPLE_COILS: 15,
        WRITE_MULTIPLE_REGISTERS: 16,
    },
    DEFAULT_RETRY_COUNT: 10,
    RESPONSE_TIMEOUT: 500,
    QUEUE_TIMEOUT: 50,
    END_PACKET_TIMEOUT: 15,
};